[package]
name = "screen_objects"
version = "4.13.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "screen_objects"
crate-type = ["cdylib", "rlib"]

[profile.release]
codegen-units = 1   
lto = true
opt-level = 3


[dependencies]
pixen = { git = "https://github.com/ignat10/pixen", branch = "main" }
pyo3 = "0.29.0"
serde_json = "1.0.151"
walkdir = "2.5.0"
stb_image = "0.3.0"
serde = "1.0.229"
fastrand = "2.5.0"

[dev-dependencies]
tempfile = "3.27.0"
