from pathlib import Path



class ScreenObject:
    def exists(self) -> bool: ...

    def tap(self) -> bool: ...
    
    def tap_nth(self, n: int) -> bool: ...

    def spam_tap(self, n: int, interval: float) -> bool: ...

    def tap_best(self) -> int: ...
    
    def reset_tolerance(self) -> None: ...


def device_config(adb: Path, ip: str | None) -> None: ...

def get_objects(samples_dir: Path) -> dict[str, ScreenObject]: ...

def reset_screen() -> None: ...

def screenshot() -> None: ...

def back() -> None: ...
