from pathlib import Path



class ScreenObject:
    def compare(self, offset_steps: int | None=None) -> bool: ...

    def tap(self, offset_steps: int | None=None) -> None: ...

    def spam_tap(self, n: int, interval: float) -> None: ...

    def tap_if_found(self) -> bool: ...
    
    def find_object(self) -> tuple[int, int] | None: ...

    def add_sample(self) -> None: ...


def device_config(ip: str | None) -> None: ...

def get_objects(samples_dir: Path, objects: Path) -> dict[str, ScreenObject]: ...

def reset_screen() -> None: ...
