from pathlib import Path



class ScreenObject:
    def compare(self, steps: int | None=None) -> bool: ...

    def tap(self, delay: float | None=None, steps: int | None=None, repeat: int | None=None) -> None: ...

    def tap_if_found(self) -> bool: ...
    
    def find_object(self) -> tuple[int, int] | None: ...


def get_objects(data_path: Path) -> dict[str, ScreenObject]: ...
